# Generated by Django 2.2.13 on 2020-06-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_auto_20200618_0821"),
    ]

    operations = [
        migrations.CreateModel(
            name="GVHVMBN",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nbvvnb", models.BigIntegerField()),
            ],
        ),
    ]
