# Generated by Django 2.2.13 on 2020-06-18 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_gvhvmbn"),
    ]

    operations = [
        migrations.RemoveField(model_name="customtext", name="ftghryuj5y",),
        migrations.RemoveField(model_name="customtext", name="sfasdfasz",),
        migrations.RemoveField(model_name="ghvhggfgvcafvwse", name="sdfaef",),
        migrations.RemoveField(model_name="homepage", name="werqwrf",),
    ]
